#!/bin/sh
conan install . --output-folder=bin --build=missing
cat conanfile.txt | sed -e '/\[generators\]/,$d' | grep -v "#ignore"| grep "/" | sed -e 's/\/.*//g' | awk '{print toupper($0)}' | sed -r 's/(.*)/find_package(\1 REQUIRED)/' > package.cmake
